name: Build and Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI?'
        required: true
        default: false
        type: boolean
      version_tag:
        description: 'Version tag (optional, for reference)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: pip install build twine

      - name: Extract and update version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          echo "Building version $VERSION"

      - name: Build wheel and sdist
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI (tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to PyPI (manual)
        if: github.event_name == 'workflow_dispatch' && inputs.publish_to_pypi
        uses: pypa/gh-action-pypi-publish@release/v1